#images
PROFILE_IMG_HEIGHT = 150
TOUR_PHOTO_IMG_HEIGHT = 300
TOUR_PHOTO_IMG_WIDTH = int(TOUR_PHOTO_IMG_HEIGHT * 16 / 9)

#truking description
DESCRIPTION_MAX_LENGTH = 100

#tour validation
TOUR_TITLE_MIN_LENGTH = 2
TOUR_TITLE_MAX_LENGTH = 100
TOUR_DESCRIPTION_MIN_LENGTH = 10
TOUR_DESCRIPTION_MAX_LENGTH = 1000
TOUR_DURATION_MIN_MINUTES = 30
TOUR_DURATION_MAX_MINUTES = 300
STOP_MIN_LENGTH = 2
STOP_MAX_LENGTH = 20

#review validation
REVIEW_COMMENT_MIN_LENGTH = 2
REVIEW_COMMENT_MAX_LENGTH = 200
